# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jingjing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://jingjingcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3821c199691240a0bc404b8ad6875f49 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d0c5d57b2d5c4fca8fafaf2df144c82b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jingjingcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3821c199691240a0bc404b8ad6875f49 }}/jingimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jingjing'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_86b6b592623446a18ec0e22fe78eaad2 }}
        images: 'jingjingcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3821c199691240a0bc404b8ad6875f49 }}/jingimage:${{ github.sha }}'